### ISSUE TITLE
Overview page `Low-level API` is not up to date

### ISSUE THREAD

**Issue by BjornTheProgrammer** [TypeScriptToLua/TypeScriptToLua.github.io#173]
The [overview](https://typescripttolua.github.io/docs/api/overview) page is not up to date. Specifically, the `Low-level API` example section is out of date. `tstl.transpile({ program })` is not a function which exists. Should be using the Transpiler class instead.

**Comment by Perryvw** [comment]
Thanks for letting me know, I have updated the documentation for the low level API with 724969ba6b9439bcba013accc80fc4a7300a6d27.
