### ISSUE TITLE
On playground, "this" function conversion related diagnostics disapear whenever code is edited

### ISSUE THREAD

**Issue by GlassBricks** [TypeScriptToLua/TypeScriptToLua.github.io#68]
This example on the playground gives an error:

https://typescripttolua.github.io/play/#code/FAFwngDgpgBAylANgM0VAzugYgVwHYwC8MAFCABYCW6AXDAG4D2lAJgDQwCGATgOZ2c8YAJREAfFyHBgAY0Z50IGAFswuPACY6CFGkzqiMZPhkhK80hWp18AazyMA7nlEBvYAF9gQA

However, as soon as any character is edited, no matter what changes are made, the `unable to convert function with a this parameter` diagnostic disapears and doesn't come back until page is reloaded.

**Comment by lolleko** [comment]
Good catch. It seems like the tstl lsp extension is unloaded somehow after updating the contents of the editor?

**Comment by GlassBricks** [comment]
I just found that, curiously, the same doesn't apply for the lua length method diagnostic:

https://typescripttolua.github.io/play#code/FDDGHsDsGcBcAJYEMBG8C89IFMDu8AZAVyQBVUAbbACgEoQIYErINFUA6Fgc1gAsQQA
